---
# PLUGINS
# ===
# See config/layers/dot-nvim/config.vim for plugin mappings

# StartUp Plugins
- repo: Shougo/dein.vim
  depends: dein.vim
- repo: rafi/awesome-vim-colorschemes
- repo: romainl/vim-cool


- repo: christoomey/vim-tmux-navigator
  if: "! (has('win32') || has('win64'))"

# GUI only:
- { repo: equalsraf/neovim-gui-shim, if: has('gui_running') }

# Vim8 only:
- { repo: roxma/nvim-yarp, if: "! has('nvim')", depends: vim-hug-neovim-rpc }
- { repo: roxma/vim-hug-neovim-rpc, if: "! has('nvim')" }
