# why use yaml to manage plugins
# see http://genkisugimoto.com/blog/manage-vim-plugins-via-yaml/
#
# StartUp Plugins
- repo: Shougo/dein.vim
  #- repo: taigacute/spaceline.vim # 状态栏 需要 nerd font 字体支持
